[versions]
# Kotlin and Gradle
kotlin = "2.2.21"
kotlinLanguage = "2.2"
jvmTarget = "21"
jetbrains-annotations = "26.0.2-1"
plugin-publish = "2.0.0"

# Jenkins
jenkins-core = "2.534"
jenkins-gradle-jpi2 = "0.55.1"

# Ecosystem BOMs
jenkins-bom = "5543.vfd758c7c868d"
jackson-bom = "2.20.1"
spring-bom = "6.2.12"
netty-bom = "4.2.7.Final"
slf4j-bom = "2.0.17"
jetty-bom = "12.1.3"
guava-bom = "33.5.0-jre"
apache-log4j-bom = "2.25.2"
vertx-bom = "5.0.5"

# Testing BOMs
junit-bom = "6.0.0"
mockito-bom = "5.20.0"
testContainers-bom = "2.0.1"

# Quality
spotbugs = "6.4.4"
detekt = "1.23.8"
spotless = "8.0.0"
ktlint = "1.7.1"
owaspCheck = "12.1.8"
kover = "0.9.3"
dokka = "2.1.0"
pit = "1.15.0"
checkstyle = "12.1.1"
jacoco = "0.8.14"
pmd = "7.18.0"
codenarc = "3.6.0"
node-gradle = "7.1.0"
cpd = "3.5"
palantir-java = "2.81.0"

# Testing
kotest = "6.0.4"
mockk = "1.14.6"
assertj = "4.0.0-M1"
spock-core = "1.3-groovy-2.4"

# Publishing
maven-gradle-publish = "0.34.0"

# Miscellaneous
jgit = "7.4.0.202509020913-r"
node = "24.8.0"
restrictImports = "3.0.0"

[libraries]
# Kotlin and Gradle
kotlin-bom = { module = "org.jetbrains.kotlin:kotlin-bom", version.ref = "kotlin" }
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
jetbrains-annotations = { module = "org.jetbrains:annotations", version.ref = "jetbrains-annotations" }

# Jenkins
jenkins-core = { module = "org.jenkins-ci.main:jenkins-core", version.ref = "jenkins-core" }
jenkins-gradle-jpi2 = { module = "org.jenkins-ci.jpi2:org.jenkins-ci.jpi2.gradle.plugin", version.ref = "jenkins-gradle-jpi2" }

# BOMs
jenkins-bom-coordinates = { module = "io.jenkins.tools.bom:bom-2.516.x", version.ref = "jenkins-bom" }
spring-bom-coordinates = { module = "org.springframework:spring-framework-bom", version.ref = "spring-bom" }
jackson-bom-coordinates = { module = "com.fasterxml.jackson:jackson-bom", version.ref = "jackson-bom" }
junit-bom-coordinates = { module = "org.junit:junit-bom", version.ref = "junit-bom" }
jetty-bom-coordinates = { module = "org.eclipse.jetty:jetty-bom", version.ref = "jetty-bom" }
slf4j-bom-coordinates = { module = "org.slf4j:slf4j-bom", version.ref = "slf4j-bom" }
netty-bom-coordinates = { module = "io.netty:netty-bom", version.ref = "netty-bom" }
guava-bom-coordinates = { module = "com.google.guava:guava-bom", version.ref = "guava-bom" }
log4j-bom-coordinates = { module = "org.apache.logging.log4j:log4j-bom", version.ref = "apache-log4j-bom" }
vertx-bom-coordinates = { module = "io.vertx:vertx-stack-depchain", version.ref = "vertx-bom" }
mockito-bom-coordinates = { module = "org.mockito:mockito-bom", version.ref = "mockito-bom" }
testContainers-bom-coordinates = { module = "org.testcontainers:testcontainers-bom", version.ref = "testContainers-bom" }

# Quality
spotless-gradle-plugin = { module = "com.diffplug.spotless:com.diffplug.spotless.gradle.plugin", version.ref = "spotless" }
detekt-gradle-plugin = { module = "io.gitlab.arturbosch.detekt:detekt-gradle-plugin", version.ref = "detekt" }
spotbugs-gradle-plugin = { module = "com.github.spotbugs:com.github.spotbugs.gradle.plugin", version.ref = "spotbugs" }
kover-gradle-plugin = { module = "org.jetbrains.kotlinx:kover-gradle-plugin", version.ref = "kover" }
pit-gradle-plugin = { module = "info.solidsoft.gradle.pitest:gradle-pitest-plugin", version.ref = "pit" }
owasp-depcheck-gradle-plugin = { module = "org.owasp:dependency-check-gradle", version.ref = "owaspCheck" }
node-gradle-plugin = { module = "com.github.node-gradle:gradle-node-plugin", version.ref = "node-gradle" }
dokka-gradle-plugin = { module = "org.jetbrains.dokka:dokka-gradle-plugin", version.ref = "dokka" }
cpd-gradle-plugin = { module = "de.aaschmid:gradle-cpd-plugin", version.ref = "cpd" }
checkstyle-gradle-plugin = { module = "com.puppycrawl.tools:checkstyle", version.ref = "checkstyle" }
pmd-gradle-plugin = { module = "net.sourceforge.pmd:pmd", version.ref = "pmd" }
jacoco-gradle-plugin = { module = "org.jacoco:org.jacoco.core", version.ref = "jacoco" }
codenarc-gradle-plugin = { module = "org.codenarc:CodeNarc", version.ref = "codenarc" }
palantir-java-format = { module = "com.palantir.javaformat:gradle-palantir-java-format", version.ref = "palantir-java" }

# Testing
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher" }
kotest-assertions-core = { module = "io.kotest:kotest-assertions-core", version.ref = "kotest" }
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
mockito-core = { module = "org.mockito:mockito-core" }
mockito-junit-jupiter = { module = "org.mockito:mockito-junit-jupiter" }
spock-core = { module = "org.spockframework:spock-core", version.ref = "spock-core" }
assertj-core = { module = "org.assertj:assertj-core", version.ref = "assertj" }

# Miscellaneous
jgit-gradle-plugin = { module = "org.eclipse.jgit:org.eclipse.jgit", version.ref = "jgit" }
restrictImports-plugin = { module = "de.skuzzle.restrictimports:de.skuzzle.restrictimports.gradle.plugin", version.ref = "restrictImports" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
plugin-publish = { id = "com.gradle.plugin-publish", version.ref = "plugin-publish" }
maven-gradle-publish = { id = "com.vanniktech.maven.publish", version.ref = "maven-gradle-publish" }
